AWSTemplateFormatVersion: '2010-09-09'
Description: EventBridge Replay + Archive Pattern

Resources:

  ###############################################
  # Archive for CDC Events from app.dynamodb
  ###############################################
  EventArchive:
    Type: AWS::Events::Archive
    Properties:
      ArchiveName: OutboxEventArchive
      Description: Archive for CDC events from DynamoDB outbox
      SourceArn: !GetAtt EventBus.Arn
      EventPattern:
        source:
          - "app.dynamodb"

  ###############################################
  # Custom Event Bus for Isolation (optional)
  ###############################################
  EventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: outbox-event-bus

  ###############################################
  # Lambda Function to Receive Replayed Events
  ###############################################
  ReplayTargetLambda:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.11
      Handler: index.lambda_handler
      Timeout: 10
      Role: !GetAtt ReplayLambdaRole.Arn
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              print("🔁 Replayed Event:", event)

  ###############################################
  # IAM Role for Replay Lambda
  ###############################################
  ReplayLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ReplayLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  ###############################################
  # Rule for Replayed Events to Target Lambda
  ###############################################
  ReplayRule:
    Type: AWS::Events::Rule
    Properties:
      Name: OutboxReplayRule
      EventBusName: !Ref EventBus
      EventPattern:
        source:
          - "app.dynamodb"
      Targets:
        - Id: ReplayLambdaTarget
          Arn: !GetAtt ReplayTargetLambda.Arn

  ###############################################
  # Permission for EventBridge to Invoke Lambda
  ###############################################
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ReplayTargetLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ReplayRule.Arn

Outputs:
  ArchiveName:
    Value: !Ref EventArchive
    Description: Name of the EventBridge archive
  EventBusName:
    Value: !Ref EventBus
    Description: Name of the custom event bus
  ReplayLambda:
    Value: !Ref ReplayTargetLambda
    Description: Lambda receiving replayed events
