AWSTemplateFormatVersion: '2010-09-09'
Description: Saga Pattern with Compensation Step (S3 cleanup on failure)

Resources:

  SagaOutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "saga-pattern-bucket-for-jon"

  SagaLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SagaLambdaPermissions
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: "*"

  SagaStateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StepFunctionInvokePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: "*"

  GenerateDataLambda:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.11
      Handler: index.handler
      Role: !GetAtt SagaLambdaRole.Arn
      Code:
        ZipFile: |
          import json
          import random
          def handler(event, context):
              return {
                  "id": random.randint(1000, 9999),
                  "value": random.choice(["alpha", "beta", "gamma"])
              }

  TransformDataLambda:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.11
      Handler: index.handler
      Role: !GetAtt SagaLambdaRole.Arn
      Code:
        ZipFile: |
          import json
          def handler(event, context):
              event['value'] = event['value'].upper()
              return event

  StoreToS3Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.11
      Handler: index.handler
      Role: !GetAtt SagaLambdaRole.Arn
      Environment:
        Variables:
          BUCKET: !Ref SagaOutputBucket
      Code:
        ZipFile: |
          import json, os, boto3
          s3 = boto3.client('s3')
          def handler(event, context):
              key = f"result-{event['id']}.json"
              if event.get('force_fail'):
                  raise Exception("Forced failure for test")
              s3.put_object(
                  Bucket=os.environ['BUCKET'],
                  Key=key,
                  Body=json.dumps(event)
              )
              event['written_key'] = key
              return event

  CompensationLambda:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.11
      Handler: index.handler
      Role: !GetAtt SagaLambdaRole.Arn
      Environment:
        Variables:
          BUCKET: !Ref SagaOutputBucket
      Code:
        ZipFile: |
          import json, os, boto3
          s3 = boto3.client('s3')
          def handler(event, context):
              key = event.get('written_key') or f"result-{event['id']}.json"
              try:
                  s3.delete_object(Bucket=os.environ['BUCKET'], Key=key)
                  return {"status": "compensated", "deleted_key": key}
              except Exception as e:
                  return {"status": "compensation_failed", "reason": str(e)}

  SagaStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn: !GetAtt SagaStateMachineRole.Arn
      DefinitionString:
        !Sub |
          {
            "Comment": "Saga Pattern with Compensation",
            "StartAt": "Generate",
            "States": {
              "Generate": {
                "Type": "Task",
                "Resource": "${GenerateDataLambda.Arn}",
                "Next": "Transform"
              },
              "Transform": {
                "Type": "Task",
                "Resource": "${TransformDataLambda.Arn}",
                "Next": "Store"
              },
              "Store": {
                "Type": "Task",
                "Resource": "${StoreToS3Lambda.Arn}",
                "Catch": [
                  {
                    "ErrorEquals": ["States.ALL"],
                    "Next": "Compensate"
                  }
                ],
                "End": true
              },
              "Compensate": {
                "Type": "Task",
                "Resource": "${CompensationLambda.Arn}",
                "End": true
              }
            }
          }

Outputs:
  SagaStateMachine:
    Description: The Step Function State Machine with Compensation
    Value: !Ref SagaStateMachine

  SagaOutputBucket:
    Description: S3 Bucket for storing and deleting files
    Value: !Ref SagaOutputBucket
